### ISSUE TITLE
Use gRPC instead of go-swagger 

### ISSUE THREAD

**Issue by drgarcia1986** [luizalabs/teresa-api#203]
### Macro vision checklist:
- [x] Login ( #185 )
- [x] create user ( #192 #200 )
- [x] delete user ( #190 )
- [x] create team ( #189 )
- [x] team list ( #197 )
- [x] team add-user ( #193 )
- [x] app create ( #207  )
- [x] app env-set ( #213 )
- [x] app env-unset ( #213 )
- [x] app info (#208)
- [x] app list ( #244 )
- [X] app logs ( #205 )
- [x] deploy ( #211  )
----------
### Extras:
- [x] set-password command ( #185 )
- [x] [server] create super user command ( #198 )
- [x] TLS (some PRs of series) 
- [x] Release command phase ( #226 )
- [x] Health Check ( #230 )
- [x] Version by tag (git) ( #229 )
- [x] minio slug storage ( #236 )
---------
### Refactorings:
- [x] cli configs ( #188 )
- [x] bash completion ( #187 ) 
- [x] delete build pods after work ( #211 )
- [x] standardize errors msgs format and server logs (server and client) ( #214 #218  )
---------
### Fun Stuff
- [X] Unit Tests
- [X] Travis CI (run unit tests against some golang versions ) ( #194 )

**Comment by drgarcia1986** [comment]
The command `team list` doesn't returns the team members list if called for a non-admin user.

**Comment by drgarcia1986** [comment]
🎉
